# Basic Information 
title: Luca Barbato
position: MRes/Ph.D. Candidate
affiliation: London School of Economics (LSE)
email: l.barbato1 at lse.ac.uk  # replace if you'd like your real email public

# Search Engine Optimization (SEO)
keywords: organizational economics, personnel economics, labour economics, applied microeconomics, LSE
description: Luca Barbato is a third-year MRes/Ph.D. student in Economics & Management at the LSE. Applied microeconomist interested in Personnel, Labour, and Organisational Economics.
canonical: https://barbatoluca.github.io/

# Links 
# Delete any you don't want to show.
# google_scholar: https://scholar.google.com/   # add if/when you have one
cv_link: assets/files/Luca_Barbato_CV.pdf
# github_link: https://github.com/barbatoluca
linkedin: https://www.linkedin.com/in/luca-barbato-26bb69189/
twitter: https://x.com/l_barbato_econ # remove if unused
website: https://www.lse.ac.uk/people/luca-barbato

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Sans Serif"  # or "Serif"

# (Remove if you don't use Google Analytics)
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
